version: "3.9"

services:
  db:
    image: postgres:16
    container_name: cineconnect-postgres
    restart: always
    environment:
      POSTGRES_USER: cineconnect
      POSTGRES_PASSWORD: cineconnect_pwd
      POSTGRES_DB: cineconnect_db
    ports:
      - "5432:5432"
    volumes:
      - cineconnect_db_data:/var/lib/postgresql/data

volumes:
  cineconnect_db_data: