version: "3.9"

services:
  db:
    image: postgres:16
    container_name: dollyzoom-postgres
    restart: always
    environment:
      POSTGRES_USER: dollyzoom
      POSTGRES_PASSWORD: dollyzoom_pwd
      POSTGRES_DB: dollyzoom_db
    ports:
      - "5432:5432"
    volumes:
      - dollyzoom_db_data:/var/lib/postgresql/data

volumes:
  dollyzoom_db_data: